# Generated by Django 2.0.7 on 2018-10-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='sum_score',
            field=models.PositiveSmallIntegerField(blank=True, db_column='总分', default=0, null=True, verbose_name='总分'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='class_rank',
            field=models.PositiveSmallIntegerField(blank=True, db_column='班级排名', default=1, null=True, verbose_name='班级排名'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='grade_rank',
            field=models.PositiveSmallIntegerField(blank=True, db_column='年级排名', default=1, null=True, verbose_name='年级排名'),
        ),
    ]
