# Generated by Django 2.0.7 on 2018-10-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20181007_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='class_rank',
            field=models.PositiveSmallIntegerField(blank=True, db_column='班级排名', default=0, null=True, verbose_name='班级排名'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='grade_rank',
            field=models.PositiveSmallIntegerField(blank=True, db_column='年级排名', default=0, null=True, verbose_name='年级排名'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='month_score',
            field=models.PositiveSmallIntegerField(blank=True, db_column='月考分', default=1, null=True, verbose_name='月考分'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='week_score',
            field=models.PositiveSmallIntegerField(blank=True, db_column='周考分', default=1, null=True, verbose_name='周考分'),
        ),
    ]
