# Generated by Django 2.0.7 on 2018-10-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20181007_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='month_score',
            field=models.DecimalField(blank=True, db_column='月考分', decimal_places=4, default=1, max_digits=10, null=True, verbose_name='月考分'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='sum_score',
            field=models.DecimalField(blank=True, db_column='总分', decimal_places=4, default=0, max_digits=10, null=True, verbose_name='总分'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='week_score',
            field=models.DecimalField(blank=True, db_column='周考分', decimal_places=4, default=1, max_digits=10, null=True, verbose_name='周考分'),
        ),
    ]
