# Generated by Django 2.0.7 on 2018-10-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20181007_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='sum_score',
            field=models.FloatField(blank=True, db_column='总分', default=0, null=True, verbose_name='总分'),
        ),
    ]
