# Generated by Django 2.0.7 on 2018-10-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20181007_2108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
