# Generated by Django 2.0.7 on 2018-10-11 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_delete_testmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examlist',
            options={'verbose_name': '考试列表', 'verbose_name_plural': '考试列表'},
        ),
        migrations.AlterModelOptions(
            name='scoreinfo',
            options={'verbose_name': '成绩列表', 'verbose_name_plural': '成绩列表'},
        ),
        migrations.AlterUniqueTogether(
            name='examlist',
            unique_together={('time',)},
        ),
        migrations.AlterUniqueTogether(
            name='rewardpunishinfo',
            unique_together={('student',)},
        ),
        migrations.AlterUniqueTogether(
            name='scoreinfo',
            unique_together={('file_number', 'which_exam')},
        ),
    ]
