# Generated by Django 2.0.7 on 2018-10-11 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20181011_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreinfo',
            name='file_number',
            field=models.ForeignKey(db_column='学生', on_delete=django.db.models.deletion.CASCADE, to='students.StudentInfo', verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='scoreinfo',
            name='which_exam',
            field=models.ForeignKey(db_column='考试', on_delete=django.db.models.deletion.CASCADE, to='students.ExamList', verbose_name='考试'),
        ),
    ]
