# Generated by Django 2.0.7 on 2018-10-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('number', models.IntegerField(db_column='教师序号', primary_key=True, serialize=False, verbose_name='教师序号')),
                ('name', models.CharField(db_column='姓名', default='male', max_length=5, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, db_column='性别', default='男', max_length=10, null=True, verbose_name='性别')),
                ('password', models.CharField(db_column='密码', default='xxxxxx', error_messages={'max_length': '不超过十六位'}, max_length=16, verbose_name='密码')),
                ('is_class_leader', models.BooleanField(db_column='是否为班主任', default=False, verbose_name='是否为班主任')),
                ('email', models.EmailField(db_column='邮箱', help_text='该邮箱将用来验证登录', max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(db_column='联系电话', error_messages={'max_length': '手机号最多十一位'}, help_text='请输入正确的联系方式', max_length=11, verbose_name='电话')),
                ('ID', models.CharField(db_column='身份证号', error_messages={'max_length': '身份证最多十八位', 'unique': '身份证号错误'}, help_text='请输入真实的身份证号', max_length=18, verbose_name='身份证号')),
                ('subject', models.CharField(blank=True, db_column='教授科目', default='', help_text='您教授的科目，如：语文', max_length=25, null=True, verbose_name='教授科目')),
                ('remark', models.TextField(blank=True, db_column='备注', default='', error_messages={'max_length': '备注不超过一百个字'}, help_text='备注不超过一百个汉字', max_length=100, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': '教师信息表',
                'verbose_name_plural': '教师',
                'verbose_name': '教师',
            },
        ),
    ]
