# Generated by Django 2.0.7 on 2018-10-07 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='header',
            field=models.ForeignKey(db_column='班主任档案号', limit_choices_to={'is_class_leader': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.TeacherInfo', verbose_name='班主任档案号'),
        ),
    ]
