# Generated by Django 2.0.7 on 2018-10-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='email',
            field=models.EmailField(blank=True, db_column='邮箱', max_length=254, null=True, verbose_name='邮箱'),
        ),
    ]
