# Generated by Django 2.0.7 on 2018-10-07 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20181007_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='biology_teacher',
            field=models.ForeignKey(blank=True, db_column='生物老师', limit_choices_to={'subject': '生物'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biology_teacher_class', to='teachers.TeacherInfo', verbose_name='生物老师'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='chemistry_teacher',
            field=models.ForeignKey(blank=True, db_column='化学老师', limit_choices_to={'subject': '化学'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chemistry_teacher_class', to='teachers.TeacherInfo', verbose_name='化学老师'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='chinese_teacher',
            field=models.ForeignKey(blank=True, db_column='语文老师', limit_choices_to={'subject': '语文'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chinese_teacher_class', to='teachers.TeacherInfo', verbose_name='语文老师'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='english_teacher',
            field=models.ForeignKey(blank=True, db_column='英语老师', limit_choices_to={'subject': '英语'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='english_teacher_class', to='teachers.TeacherInfo', verbose_name='英语老师'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='geography_teacher',
            field=models.ForeignKey(blank=True, db_column='地理老师', limit_choices_to={'subject': '地理'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geography_teacher_class', to='teachers.TeacherInfo', verbose_name='地理老师'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='history_teacher',
            field=models.ForeignKey(blank=True, db_column='历史老师', limit_choices_to={'subject': '历史'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_teacher_class', to='teachers.TeacherInfo', verbose_name='历史老师'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='math_teacher',
            field=models.ForeignKey(blank=True, db_column='数学老师', limit_choices_to={'subject': '数学'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='math_teacher_class', to='teachers.TeacherInfo', verbose_name='数学老师'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='music_teacher',
            field=models.ForeignKey(blank=True, db_column='音乐老师', limit_choices_to={'subject': '音乐'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='music_teacher_class', to='teachers.TeacherInfo', verbose_name='音乐老师'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='physical_teacher',
            field=models.ForeignKey(blank=True, db_column='物理老师', limit_choices_to={'subject': '物理'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_teacher_class', to='teachers.TeacherInfo', verbose_name='物理老师'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='politics_teacher',
            field=models.ForeignKey(blank=True, db_column='政治老师', limit_choices_to={'subject': '政治'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='politics_teacher_class', to='teachers.TeacherInfo', verbose_name='政治老师'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='sport_teacher',
            field=models.ForeignKey(blank=True, db_column='体育老师', limit_choices_to={'subject': '体育'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sport_teacher_class', to='teachers.TeacherInfo', verbose_name='体育老师'),
        ),
    ]
