# Generated by Django 2.0.7 on 2018-10-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20181012_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='remark',
            field=models.TextField(blank=True, db_column='备注', default='', error_messages={'max_length': '备注不超过一百个字'}, help_text='备注不超过一百个汉字', max_length=100, null=True, verbose_name='备注'),
        ),
    ]
