# Generated by Django 2.0.7 on 2018-10-11 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20181011_2123'),
        ('administrator', '0003_auto_20181007_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classinfo',
            options={'verbose_name': '班级信息', 'verbose_name_plural': '班级信息'},
        ),
        migrations.AlterModelOptions(
            name='dormitoryinfo',
            options={'verbose_name': '宿舍', 'verbose_name_plural': '宿舍'},
        ),
        migrations.AlterModelOptions(
            name='gradeinfo',
            options={'verbose_name': '年级信息', 'verbose_name_plural': '年级信息'},
        ),
        migrations.AlterUniqueTogether(
            name='classinfo',
            unique_together={('grade', 'class_number', 'header')},
        ),
        migrations.AlterUniqueTogether(
            name='gradeinfo',
            unique_together={('grade_number', 'year')},
        ),
    ]
